### ISSUE TITLE
TINU 2.1: No Install App in Applications=crash

### ISSUE THREAD

**Issue by leemacabre** [ITzTravelInTime/TINU#8] opened 2019-06-10 14:32 UTC
Going to use TINU. 
Old late 2009 iMac, 10.13.6  so have stored Mac OS Installers elsewhere. 
Forgot to copy Mac OS Installer to Applications folder, invoked TINU and of course no Mac OS Installer found TINU=crash.
Maybe quick check Mac OS Install App is there and if not, tell user =idiot?
HTH?

(Heard U accident? Hope getting better.)

**Comment by ITzTravelInTime** [comment] 2019-06-10 18:32
The problem is for caused not by the absence of an installer app, i am not so dumb to not have took into account that there will be users trying to use tinu without an installer app, so in case of no installer apps it will just show you an error messaage and give you some actions, like an option to open an installer app not loaceted into the directroies tinu looks into (that opion is always a vailable btw) or a page full of links for installer app on the app store.

The problem you are experiencing is probaly caused by a known issue with this version which is an error with the resolution of finder aliases which is not handeled correctly, it will be fixed in the next release of tinu coming this month, but i can start giving you a beta of the new version to to let you check if the error shows again.

If you don't want to try the new version, just send me the text of the diagnostics mode of tinu (menu bar->tinu->diagnostics mode) and let's try to figure out the exact issue from that.

PS Don't always assume that a cause of an issue is what you think at first thougt, many times it's a different cause, in this case i guarantee you that it's not caused by the assence of the installer app, it's very likely that bug i have mentioned, i know my code.

**Comment by ITzTravelInTime** [comment] 2019-06-12 11:25
Check if the problem is still there once you copy the installer app, it's not linked to the installer app presence, but to a known bug with finder aliases which has been fixed for the next release of TINU

**Comment by leemacabre** [comment] 2019-06-12 13:32
Hello Pietro, tried with 10.14.5 image in Apps and crashed. Attached crash
window. 
Put TINU in Diagnostic mode and got Error 1, can¹t be used?

tony

**Comment by ITzTravelInTime** [comment] 2019-06-12 13:40
Hi i need all the text which appers in the terminal window using diagnostics mode, because all the text allows me to locate the issue precisely

**Comment by leemacabre** [comment] 2019-06-12 13:47
When I invoke Diagnostics mode it won¹t let me. Says can¹t be used error 1?

tony

**Comment by ITzTravelInTime** [comment] 2019-06-12 13:49
put tinu in the applications folder and run this command in a terminal widnow: /Applications/TINU.app/Contents/MacOS/TINU

**Comment by leemacabre** [comment] 2019-06-12 14:22
Done. 
Still crashed. 
Presumably attached will help.

tony

**Comment by ITzTravelInTime** [comment] 2019-06-12 22:20
Have you done any modding to the os? have you installed some particular things? it's wired that it crashes when you try to open the app's executable from the terminal, so the problem is more complex than i tought, we should examinate better your case, can you attac screenshotf of all the issues? including the details of the crashyou got with the installer app selection screen

**Comment by ITzTravelInTime** [comment] 2019-06-12 23:02
Ps, i can't see your email attachments because this is a github issues threads, please send me the attachments at: piecaruso97@gmail.com

**Comment by leemacabre** [comment] 2019-06-13 02:49
Hello Pietro,

OS is standard 10.13.6. I run Sophos antivirus. Never had a virus. Boot OS
on SSD and backed-up to internal HD (this has confused 1Password as it sees
2 Apps on update)

Attachments: TINU crash.zip ­ when I had no App in Applications, it¹s the
crash window. Lastlogin.zip Is the record from TINU when TINU in
Applications and your Terminal instruction used.

Reading the log I note TINU crashed when TOR alias met on Mojave TEST
volume. I played with TOR a long time ago and removed it. I forgot it was on
this Volume. I removed TOR App and TOR Alias now.
----------------------
SUCCESS:
As TOR & it¹s Alias removed from Mojave TEST Volume I try again.

I only had USB with 14.5 installer on made with Terminal using Apple
command, so I used it.

TINU in Applications; 14.5 Installer in Applications; used your Terminal
command to start.

Worked well! Attachment TINU success.zip. Nice USB image. There¹s a spelling
error in the top of the pane while it¹s being made -²Bootale² should be
³Bootable²
---------------------
Here¹s my guess: When TOR removed from boot volume long ago it left an
orphan alias. When Mojave TEST Volume made all items from boot Volume
transferred so this orphan alias got transferred. So the orphan alias the
problem?
============
I have an ASROCK mobo to Hack so will be using TINU USB. Will try the Clover
part to start. 

Tony
====

**Comment by ITzTravelInTime** [comment] 2019-06-13 11:06
Great at the end it was that known error with aliases, it's caused by an error misshandled in the code that resolves aliases, so when userolvable aliases are found the app crashes, that has already been fixed in my development builds for version 2.2 (i just reworked that code to work by throwing optionals instead of errors and also by reworking the pasrt that uses it, now it's way better and more elegant as an implemenmtation) and thank you very mutch for telling me about spelling mistakes, i do a lot of them and so this helps quite a lot to improove the app. The terminal command is no longer required to run tinu since it's only amin is to let you to read the diagnostics log built into the app. For the mac os install, yours is quite clean and the issue is caused by that one little bug with the alias resolution, the next version of the app (2.2) coming this month will fix that.

**Comment by ITzTravelInTime** [comment] 2019-06-13 11:15
You can join the TINU's beta testing group on Telegram to try out the new version.
https://t.me/TINUBetaTesting

**Comment by ITzTravelInTime** [comment] 2019-06-14 23:06
So we figured out that the issue was a known problem with orphaned aliases, that has already been fixed in the beta of the upcoming relese, so we no longer need this thread, and i am going to close it. If you need any help go to the telegram group i linked in my previous message or send me an email at: piecaruso97@gmail.com

Bye and ejoy your installer drives!

PS:  for the clover and the hackintosh reeted stuff it's better to go to the insanelymac forum or to the hackintosh subreddit, for some desktop system i can help you as well, but remeber that lover needs to be proprly installed and configured according to the hw specs of the target machine, the target machine must use parts which are compatible with mac os, and you need also think about using the proper specs for your machine, it's not an easy task, but with learning and patience you can master it.

**Closed by ITzTravelInTime** 2019-06-14 23:06 UTC

**Comment by ITzTravelInTime** [comment] 2019-06-17 01:21
after extensive testing on the beta seems that the issue with orphaned aliases is still there, i will spend the next session of work to fix it, i will keep you updated
